services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: bitespeed_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/bitespeed_db?schema=public
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata: